### ISSUE TITLE
scalar multiplication

### ISSUE THREAD

**Issue by jarrodwb** [to-ithaca/libra#10]
How would I get something like,
```scala
assert(3 * 3.m == 9.m)
assert(3.m * 3 == 9.m)
```
to pass?

After,

```scala
scala> import spire.implicits._, libra._, libra.si._
import spire.implicits._
import libra._
import libra.si._
```
I get, 

``` scala
scala> 3 * 3.m
<console>:27: error: could not find implicit value for parameter ev: spire.algebra.Ring[libra.QuantityOf[Int,libra.si.package.Length]]
       3 * 3.m
```
and
```scala
scala> 3.m * 3
<console>:27: error: type mismatch;
 found   : Int(3)
 required: libra.Quantity[Int,?]
       3.m * 3
             ^
```
Maybe I just need to import something from spire or some other import?

**Comment by zainab-ali** [comment]
Scalar multiplication should now be supported with spire's module.  For example:
```
3.0.m :* 3.0
```

Thanks for raising this!  `libra` is still in it's early stages, so there are probably lots of features missing.  Please keep letting us know if you need anything, so we can fix the issues.

**Comment by jarrodwb** [comment]
It works! Thanks and I will let you know how it goes as I continue to use your project. :+1:
