### ISSUE TITLE
coulomb

### ISSUE THREAD

**Issue by erikerlandson** [to-ithaca/libra#21]
Hi @zainab-ali,
This is a funny way to get in touch, but I couldn't find any email or other social media handles.  I saw your scheduled topic for typelevel summit on Libra, and wanted to compare notes; I've been working on a similar project that uses macros to do compile-time manipulation of unit types:
https://github.com/erikerlandson/coulomb
My email is erikerlandson@yahoo.com or eje@redhat.com

**Comment by zainab-ali** [comment]
Hi Erik,
Thanks!  Coulomb looks really interesting - I'll drop you an email shortly
