### ISSUE TITLE
Idea: domain-specific (eg SI-units) library on top of Libra?

### ISSUE THREAD

**Issue by benhutchison** [to-ithaca/libra#25]
Brilliant talk today at Typelevel summit, congrats!

Just capturing a conversation we had about how the Libra's functionality could be consumed by end
 users in industry now, without requiring the Typelevel compiler, which I sense might be a deal breaker for alot of users. 

IIUC, the Typelevel compiler is only needed to express the number types & type-arithmetic. But if domain-specific libraries were built that exposed methods like `m`, `kg`, `secs` that lift ordinary numbers into dimensioned types, then these binaries could be used by clients running the lightbend compiler I think.

**Comment by zainab-ali** [comment]
Thanks! 
It would be great to remove the dependency on TLS for end users.  Having taken a closer look, this can be done by removing `ValueOf` in favour of singleton-ops's `SafeInt`.

The next step is to provide domain specific libraries, as you suggest above.  This should be really easy, as it just involves enriching the `si` package, or adding more such packages.

I'll start weeding out `ValueOf`.

**Comment by benhutchison** [comment]
Ah the quaint concepts of times past... "the Typelevel compiler"... "lightbend compiler"
