### ISSUE TITLE
NoSuchMethodError when trying out examples

### ISSUE THREAD

**Issue by erikerlandson** [to-ithaca/libra#28]
I was trying out the "tl/dr" example [here](https://to-ithaca.github.io/libra/), and it isn't recognizing the operators.

I added the following to my project build.sbt:

```scala
  .settings(resolvers += "fthomas" at "https://dl.bintray.com/fthomas/maven/")
  .settings(scalaOrganization := "org.typelevel")
  .settings(scalacOptions += "-Yliteral-types")
  .settings(libraryDependencies += "com.github.to-ithaca" %% "libra" % "0.2.0")
```
Then I ran the following in my repl, which resulted in the errors shown below:

```scala
Welcome to Scala 2.11.8 (OpenJDK 64-Bit Server VM, Java 1.8.0_131).
Type in expressions for evaluation. Or try :help.

scala> import spire.implicits._, libra._, libra.si._
import spire.implicits._
import libra._
import libra.si._

scala> val w = 1.0.m
w: libra.QuantityOf[Double,libra.si.package.Length,libra.si.package.Metre] = Quantity(1.0)

scala> w + w
java.lang.NoSuchMethodError: libra.ops.quantity$Add$.quantityAdd(Lalgebra/ring/AdditiveSemigroup;Lshapeless/ops/hlist$Align;)Llibra/ops/quantity$Add;
  ... 42 elided

scala> w * w
java.lang.NoSuchMethodError: libra.ops.quantity$Multiply$.quantityMultiply(Lalgebra/ring/MultiplicativeSemigroup;Llibra/ops/dimensions$Multiply;)Llibra/ops/quantity$Multiply;
  ... 42 elided

scala> 
```

**Comment by erikerlandson** [comment]
If I check out the libra repo itself (v0.2.0 tag) and run the example in `sbt console`, that _does_ work.

**Comment by zainab-ali** [comment]
That's very bizarre.  I've created a working [libra example project](https://github.com/to-ithaca/libra-example).  What are the differences between your project and this one?

**Comment by erikerlandson** [comment]
The only difference that leaps out is that I was building with scala 2.11.8.  I also included `-Yliteral-types`.  There was other build config in the sbt file, as I was using the coulomb repo, but none of it seemed orthogonal to libra concerns

**Comment by zainab-ali** [comment]
This [branch](https://github.com/zainab-ali/libra-example/tree/scala-2-11-literal-types) uses `Yliteral-types` and scala 2.11.8, but unfortunately I can't get the errors shown above.  Do you have a gist of your `build.sbt`?

**Comment by erikerlandson** [comment]
Unfortunately, I clobbered my original edits.  Basically, it would have been the [coulomb build.sbt](https://github.com/erikerlandson/coulomb/blob/develop/build.sbt) with the Libra config added to the`examples` sub-project.

It's not altogether sane to try and run Libra from the `coulomb` build.sbt file, anyway :)  Given that you're not reproducing the error, I think what I'll do is close this issue; I can re-open it if I run into anything similar with a fresh build.sbt
