### ISSUE TITLE
Add support for ScalaJS

### ISSUE THREAD

**Issue by zainab-ali** [to-ithaca/libra#33]
This follows from a discussion with @cquiroz about Libra adoption.
Potentially many users need ScalaJS support.

Spire, shapeless and singleton-ops all support this, so it should be trivial to add.

**Comment by zainab-ali** [comment]
ScalaJS would make the build matrix much larger, and consequently would cause an explosion in build times.  I'd be happy to support this, but only if someone actually has a use for it.

If anyone does want to use libra with ScalaJS, please comment here.

**Comment by cquiroz** [comment]
Build times tend to be larger for scala.js in any case and i guess it will double the matrix size right? i haven't followed this up as i wasn't able to update singleton-ops but now that you did I may give it a try

**Comment by zainab-ali** [comment]
Yes, it would double the build times.  Our build times are pretty small compared to most projects (5 - 6 minutes), so I'm happy to double them as long as someone has a use case.  Adding ScalaJS should be fairly straightforward.

**Comment by cquiroz** [comment]
The changes aren't that big but i'm having troubles running tests on the JS side. I'll let you know if I can make it work

**Comment by maekl** [comment]
I needed this and have a working implementation apart from a single failing [test](https://github.com/to-ithaca/libra/blob/641f3540e521fc716d67bc652ccd68d8b6bd229a/core/src/test/scala/libra/QuantitySpec.scala#L93). `Double.toString` does not behave the same way in ScalaJS as on the jvm. It can be solved using platform-specific code (see for example how it was solved in [squants](https://github.com/typelevel/squants/blob/master/js/src/main/scala/squants/Platform.scala))

The new directory layout would be:

```
.
├── core
        ├── js
        ├── jvm
        └── shared
```

If this sounds ok I'd be happy to wrap it up in a PR

---

I have submitted an idea (https://github.com/to-ithaca/libra/issues/108) which I think would provide another way to solve the platform differences (with the help of `scala-java-locales`)

**Comment by maekl** [comment]
Turns out platform specific code isn't required. Doubles just have to formatted with something like `"%.1f".format(d)`. Not easily done with the current code without something like #108 AFAICT

An alternative view is that nice & predictable formatting isn't (at least not yet) an important feature. After all, `(0.1d + 0.2d).toString == "0.30000000000000004"` is true. So, it might make sense to just update the failing test use a number that produces the same result on both platforms.

**Comment by zainab-ali** [comment]
Thanks @maekl ! As stated in #108 , I think we could do with a `ShowMagnitude` typeclass.

I'd be very happy to include ScalaJS.  Please feel free to submit a PR for it.

**Comment by maekl** [comment]
I have submitted a PR. However, I did run into a few issues, mostly around the microsite in combination with cross-compilation. Tried fixing them with minimal dependency upgrades but ran into even more incompatibility issues. I could only make it work by upgrading the Scala versions as well as many other dependencies of the project.

**Comment by zainab-ali** [comment]
This has been merged in :tada: 
I'm aiming for a release later today

**Comment by zainab-ali** [comment]
This has been release in v0.7.0.  Thanks @maekl !  

Please feel free to open a PR and add yourself to the list of [contributors](https://github.com/to-ithaca/libra/blob/master/CONTRIBUTING.md#contributors)
