### ISSUE TITLE
Add angular velocity units

### ISSUE THREAD

**Issue by zainab-ali** [to-ithaca/libra#38]
This follows from #37 
The following units could be added:
- radians per second
- degrees per second

**Comment by ldrygala** [comment]
hi @zainab-ali, i would like to try with this issue (it's my first attempt to contribute to open source project)

**Comment by zainab-ali** [comment]
Thanks for choosing libra for taking your first steps into open source @ldrygala  :smiley: 

I suggest that you only add units for degrees, as radians have not yet been added.

The best place to put them would be the [nonsi package](https://github.com/to-ithaca/libra/blob/master/src/main/scala/libra/nonsi/package.scala).  This is for non-si units.  

I suggest you create a type alias for `AngularVelocityQuantity` similar to the ones [here](https://github.com/to-ithaca/libra/blob/master/src/main/scala/libra/si/package.scala#L106).

After that, you can add methods for `degreesPerSecond`, `arcMinutesPerSecond` and `arcSecondsPerSecond` to the `BaseQuantityNonSiOps` [here](https://github.com/to-ithaca/libra/blob/30fd0bf6cd0000cbabfc376d2e68d829bdc81489/src/main/scala/libra/nonsi/package.scala#L39).

Please also add tests in the [NonSiSpec](https://github.com/to-ithaca/libra/blob/master/src/test/scala/libra/NonSISpec.scala).

I know that the package names and locations aren't too clear and intend to restructure them over the next few weeks.

Give me a shout if you need any advice!

**Comment by zainab-ali** [comment]
These have been added in #46 and #53
