### ISSUE TITLE
Improve colour contrast for code blocks on website

### ISSUE THREAD

**Issue by zainab-ali** [to-ithaca/libra#62]
The [libra website](https://to-ithaca.github.io/libra/) has code blocks with small grey text against a light grey background.  The poor contrast makes this difficult to read.

This can be amended by increasing the font size, or changing the style of the code blocks.

## Where to start
The libra site is generated using [sbt-microstes](https://github.com/47deg/sbt-microsites).  This has a variety of themes and configuration variables.  The [build.sbt](https://github.com/to-ithaca/libra/blob/master/build.sbt) uses the [ocean](https://github.com/47deg/sbt-microsites/blob/master/src/main/resources/highlight/styles/ocean.css) higlight theme, which might be configuring the poor contrast.

This could probably be solved by switching to a different highlight theme.

The site can be run locally using jekyll as follows:
```bash
sbt makeMicrosite
cd target/site
jekyll serve
# now navigate to localhost:4000/libra/
```

**Comment by enricsangra** [comment]
I'm changing this to `atom-one-light`.

**Comment by zainab-ali** [comment]
Thanks @enricsangra !  The new theme is much better.  Would it be ok if I added you to the contributor's list?

**Comment by enricsangra** [comment]
No problems at all! I'll continue checking the project and help wherever I can!
